#!/bin/bash

# Extract values using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/') # Capitalize first letter
formatted_height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}') # decimeters -> meters
formatted_weigh=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1/10}') # hectograms -> kg
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/') # capitalize

# Format and print
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
